using System;
using System.Net;

namespace Demo.Adventures.Common.Exceptions
{
    /// <summary>
    ///     Represents errors that are explicitly generated by the service.
    /// </summary>
    public abstract class ServiceException : Exception
    {
        public ServiceException(string message, HttpStatusCode status) : base(message)
        {
            Status = status;
        }

        /// <summary>
        ///     Error HTTP status code.
        /// </summary>
        public HttpStatusCode Status { get; }
    }
}